### ISSUE TITLE
Basic TypeScript type check error 

### ISSUE THREAD

**Issue by fasiha** [erikbrinkman/d3-dag#101]
This is a very newbie issue, forgive me. I'm working on porting the [Codepen](https://codepen.io/brinkbot/pen/oNZJXqK) example to TypeScript and am running into some TypeScipt issues that I'd love some feedback on. My tentative port is at https://codesandbox.io/s/naughty-moon-tdy3dr which generates a nice layout similar to the Codepen, but unfortunately has three `as any` that I can't figure out.
1. I need `const { width, height } = layout(dag as any);` because even though `dag` seems to have good inferred types (because I hardcode the `grafo` data), `layout` expects `Dag<never, never>`. Why? I see the note in the [Readme](https://github.com/erikbrinkman/d3-dag#typescript-notes) warning this might happen with custom operators and accessors, but I don't think I'm using anything like that?
2. (The second `as any` is in D3, not in d3-dag, so not your problem 😅. But for completeness: I need `d3.line().curve(d3.curveCatmullRom).x((d) => (d as any).x)` because `d` is expected to be `[number, number`] whereas in reality its `{x: number, y: number}`.)
3. The final `as any` is in the paths for the edges: `.attr("d", (d) => line(d.points as any))`. I need this there because otherwise TypeScript complains that `Type 'Point' is not assignable to type '[number, number]'`.

I'm happy to keep digging into these and figure out how to d3-dag and D3's types but am also most grateful for any pointers 🙇!

**Comment by erikbrinkman** [comment]
Sorry for the late response. One of the things I plan on doing is moving the code pen over to my own typescript react demo which should hopefully help some of this.

In response to your questions:
1. This is a result of you using custom accessors, specifically your use of a custom `nodeSize`. For some reason, when you left the parameter of nodeSize empty, it inferred it as taking `DagNode<never, never>`, probably because that's the widest type of function (i.e. one in which you never access the data). However, you actually want this to function for dags with any data type, so you need to properly type it as `.nodeSize((node?: d3dag.DagNode) => ...`. The `?:` is a shorthand for `DagNode | undefined`, and `DagNode` itself has default data types as `unknown`. Once you fix that typing, you no longer need to case the dag as any.
2. Unfortunately, the style of d3 is not super amenable to typescript typing. I went through great pains to try and preserve types in the appropriate way, but it's not easy. For `d3.line` it expects to know the data type when you create it, so you need to change your initial `d3.line()` to `d3.line<{ x: number; y: number}>`
3. After fixing 2, `d3.line` knows what type of data it takes and this cast is also unnecessary.

Hope that helps!

**Comment by nuttycom** [comment]
@erikbrinkman thanks for replying here; I've been running into the same issues struggling to get type inference working given the style that's used for the `Operator` builders. It would be really helpful to add some documentation about this to the API docs, because when type inference fails it's pretty opaque as to how to debug it (and I'm speaking as someone who's pretty familiar with type-level programming, though I'm fairly new to TypeScript).

**Comment by erikbrinkman** [comment]
@nuttycom could you be more specific with the issues you're facing, it's really hard to help without specifics. A few random points:
- typescripts type system is pretty different than most as in some sense it's a subtractive system, so familiarity of type systems certainly helps, but it can also mislead if you expect things to work a certain way
- If you're having trouble, it helps to type everything. Then typescript will usually error "sooner" making it easier to figure out where you went wrong.
- For the errors, unfortunately, I don't think there's much to be done as typescript is still pretty limited, and a failure here is probably unintended inference. However, even in that case, there's no way to throw explicit type errors to help. There's some open issue for typescript that I'm too lazy to link, but if that ever goes in, it'll probably be worth adopting.
- Do you have actually suggestions on how to write the documentation? Unfortunately there's no hard and fast rules that I know of that could really help. It's mostly what I say here, if you run into issues, add more types.

Things to note for myself:
- It may be worth revisiting the way operators are typed to make it more explicit. That will make certain aspects less generalizable, but may make the typing itself more clear.
- I should look into how default arguments play into type inference. It seems like for things like NodeSizeAccessor typescript may be picking default arguments if it can't infer them. If this is the case, removing default arguments may make inference "better", which in this case means defaulting accessors to `DagNode<unknown, unknown>` versus `DagNode<never, never>` although both have issues, the former is probably preferable as errors will occur inside the accessor, rather than the final inference.

**Comment by nuttycom** [comment]
I was encountering exactly the issue that the original poster mentioned, and while I was attempting to explicitly type each step of the chain of operators starting from `sugiyama()` the inferred types that VSCode was showing me were pretty opaque, full of `Up<...>` references. I was attempting to find how to explicitly ascribe the `DagNode` type, but I didn't identify `nodeSize` as the culprit. All of the essential details that I needed to find ended up being in https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama.Operators.html but I didn't find my way there until after reading your response here. I think that what might have helped me is more comprehensive documentation of the `<Ops>` type parameter of `SugiyamaOperator` - I didn't identify the `Operators` bound as being the key piece of information.

This is the first time I've encountered this "operator" pattern, and there are a lot of `*Operator` types where it's not clear how they compose (for example, it's not at all clear what operators of https://erikbrinkman.github.io/d3-dag/modules/index.html can be used together). This pattern is clearly something I'm going to have to become more familiar with, but at present I haven't really figured out what it means when something is called an `Operator` because that naming doesn't (as far as I can figure right now) match my understanding of operators that I'm drawing on from other languages.

In any case, thanks again for your response. I don't know enough about the Typescript type system to be able to make any real suggestions, but my experience from other languages does make think that top types like `unknown` often cause problems; I usually prefer to have explicit universally quantified type parameters at the top level. The fact that `<Ops>` itself isn't parameterized by the node and link parameters is likely why I didn't think to look there.

**Comment by erikbrinkman** [comment]
I think you make a good point about further detailing how the `Operators` type works, and how typescript ends up inferring the appropriate type given what you've specified.

I agree that it's not clear how they compose. Unfortunately the only real guides are the function signature, and unenforceable (from a typescript perspective) contracts on behavior. In the version I'm working on, all of the names are changed so that the interfaces specify what main interface they extend, e.g. `SimplexLayeringOperator` is an "instance" of a `SimplexOperator`, at least from a more traditional type hierarchy sense. Unfortunately, I'm not sure this is a pattern. I derived this myself from the way that d3 works and the behavior of typescript. I admit it leaves a lot to be desired.

In typescript `unknown` and it's inverse `never` are useful because they're the implicit type bounds. Everything is assignable to unknown, and never is assignable to anything. Ops could be parametrized by Node and Link data, but I found that impossible to rederive the implied type bounds by the combination of operators, whereas leaving them unspecified did. At the very least this gives me good feedback as to other concerns to factor in when thinking about usability of the type system. It's not clear to me if this is a result of not directly having higher kinded types, although maybe if it did, it would make the inference of the union types more sensible.

More notes to myself: 
- typescript doesn't simplify `Up` types, so maybe it's worth making them explicit, e.g. `{ layering: NewLayering; decross: Ops["decross"] }` if typescript will simplify for debugging purposes.

**Comment by erikbrinkman** [comment]
The updated codepen examples are written in typescript (although codepen doesn't actually run any checks 😞). I also added [some documentation](https://erikbrinkman.github.io/d3-dag/modules.html#md:ops) the Ops parameters, which should help. Feed free to reopen if things aren't clear, or you'd prefer more detail, documentation is easy to update!
