### ISSUE TITLE
Tips for writing my own layering

### ISSUE THREAD

**Issue by kelemeno** [erikbrinkman/d3-dag#103]
Hey, I would like to write my own layering operator. 

Basically, I have a binary tree, with some additional Dag edges thrown onto it (only going upward), so I would like each node to be layered as its depth in the tree.

I eventually want to influence the position of the nodes as well, to show the tree structure better. (I am already showing the tree votes differently to dag votes).

Do you have anny tips/recommendations or better alternatives?

I think I have to rewrite e.g. https://github.com/erikbrinkman/d3-dag/blob/main/src/sugiyama/layering/simplex.ts

Or maybe I could get away with specifying ranks? 

And thanks for the great repo, it's fantastic!

**Comment by erikbrinkman** [comment]
@kelemeno sorry for the late response!

- If your tree is compact, e.g. all children are one height below their parents, then simplex should just do the right thing, and so should [`longestPath`](https://erikbrinkman.github.io/d3-dag/modules/sugiyama_layering_longest_path.html#longestPath) (the later being a little faster).
- If it's not compact, you should be able to get away with just specifying ranks. It's still more computationally expensive than necessary, but it's the next easiest for your effort.
- The fastest for large trees will be writing it yourself. If you look at the documentation for [`LayeringOperator`](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering.LayeringOperator.html)s it has a pretty simple requirement
   > After calling a layering operator on a dag, every node's value should be set to a non-negative integer layer, starting at 0. Additionally children should have a strictly larger layer than their parents, and if a node has multiple links to the same child, it's layer should be at least two greater than its parent.
   If you had the depth stored in the node data you could use that with something like:
   ```ts
   function depthLayering(dag: Dag<{ myDepth: number }, unknown>): void {
       for (const node of dag) {
           node.value = node.data.myDepth;
       }
   }
   ```
   However, if you don't have the height stored, and want it purely in graph terms, then you should also be able to use [`height`](https://erikbrinkman.github.io/d3-dag/interfaces/dag.Dag.html#height) because that does exactly what you want.
   ```ts
   function depthLayering(dag: Dag<unknown, unknown>): void {
       dag.height();
   }
   ```
   Do note, that both of these implementation assume that you don't have a muultigraph, e.g. you can't have two edges between the same two nodes. Due to the way we layout multi-edges, we have to insert dummy layers, and these implementations don't do that.

**Comment by kelemeno** [comment]
Thanks this is great! 

I will use the depthLayering method you provided, I have the height stored. (I don't think the first one will work, as I will not draw every edge of the tree, only a section of the tree. But I do want to keep the tree's layering. I also don't think it is compact). 

And fortunately not a multigraph.
