### ISSUE TITLE
General question about node ordering

### ISSUE THREAD

**Issue by wallacer** [erikbrinkman/d3-dag#104]
Hello, love the work you've done here.

Hopefully this isn't a dumb question, but it's not obvious to me if there's any support for applying constraints to the layout to prefer ordering by a particular value in the data.

My specific use case is rendering git graphs, and I'm using `dagStratify` to create my dag, and `grid` as my layout operator.  I'd love to be able to specify an accessor for the nodes to sort by when being laid out.  In my case, commit timestamp.  

Another really nice feature would be to be able to specify something that would help with selecting which lane is chosen ie. in my use case it would be nice to be able to force the main branch to be lane 1, and have things diverge from there.

I'm just wondering if there's any way to accomplish that currently?  If not I'll probably just write up something purpose built for my use case.  I've been pretty impressed with the results from d3-dag so far though, so would love if I can solve this problem here.

Thanks :)

**Comment by erikbrinkman** [comment]
No dumb questions, and yes, this is possible! d3-dag is written to be modular, so almost any piece can be swapped out for your own code, but sometimes that might mean a lot of extra work. For your questions it's a mixed bag.

- **ordering** - the grid operator has an optional [`rank`](https://erikbrinkman.github.io/d3-dag/interfaces/grid.GridOperator.html#rank) accessor that can be used to specify how to order things. For your case it should be something like `grid().rank(node => node.data.commitTime)`. The rank need to be a number since typescript doesn't have a good way of specifying orderability, but you should be able to convert to a unix timestamp if its in some other format.
- **lane** - the lane assignment is also its own functionality that can be pulled out. and updated as `grid().lane(...)`. However, [lane operators](https://erikbrinkman.github.io/d3-dag/interfaces/grid_lane.LaneOperator.html) are more difficult to write. From your description, you probably want to use something like the single sided lane indexer [here](https://github.com/erikbrinkman/d3-dag/blob/main/src/grid/lane/greedy.ts). However, the tweaks necessary to get the main branch to always be lane 0 (1), might necessitate rewriting lane, which is most of the layout anyway and therefore might be easy to just spin everything up yourself. However, if you can think of a nice way to upstream the change in a way that's pretty general, or builds nicely off of the existing operators I'd welcome it.

**Comment by wallacer** [comment]
Thanks for the quick response!  The rank operator is exactly what I needed for the ordering.  Can't believe I missed it in the api docs.
The date ordering issue was actually far higher priority than lane preference.  I think I will tackle the lane operator down the road, and if I do wind up writing a new lane operator  that seems generally useful, I'll be sure to submit a PR.

Really appreciate the help.
