### ISSUE TITLE
How to plot a horizonal sugiyama graph

### ISSUE THREAD

**Issue by seahurt** [erikbrinkman/d3-dag#112]
I am tring to plot a  horizontally placed graph, but got a little problem.

Below is the original graph from https://codepen.io/brinkbot/pen/oNQwNRv
![image](https://github.com/erikbrinkman/d3-dag/assets/3347603/6d49d5c9-d359-4bd2-8ad1-e0f97468e4a2)

After swipe the x and y by following code(change from line 144):
```js
var { height, width } = layout(graph);



function TransNode(node){
  console.log("transform", node.data)
  let tmp = node.ux;
  node.ux = node.uy;
  node.uy = tmp;
}

function TransGraph(g){
  let tmp = width;
  width = height;
  height = tmp;
  
  for (let node of g.nodes()){
    TransNode(node);
  }
  for (let link of g.links()){
    let points = [];
    points.push([link.source.ux, link.source.uy]);
    points.push([link.target.ux, link.target.uy]);
    link.points = points;
  }
}

TransGraph(graph);
```

The result graph become this:
![image](https://github.com/erikbrinkman/d3-dag/assets/3347603/ae04ae30-026a-424a-a4ef-31ba28fcdacf)

It seems like the path between nodes differed.   But I don't known how to make it work. Could you please help me?

Or is there an option to plot  horizontally placed graph directly?

**Comment by erikbrinkman** [comment]
you probably missed all of the x's and y's. Fortunately, this is now built in in the form of a tweak.

When constructing the layout function, there's a line in the example:
```ts
  .tweaks([shape]);
```

All you need to do is add another tweak to flip it:
```ts
  .tweaks([shape, d3dag.tweakFlip()]);
```

The edges will still look a bit weird due to the spline interpolation of d3. To fix that, change
```ts
const line = d3.line().curve(d3.curveMonotoneY);
```
to
```ts
const line = d3.line().curve(d3.curveMonotoneX);
```

You should then see:
![image](https://github.com/erikbrinkman/d3-dag/assets/858926/9725cbe8-da17-4e44-b652-3c3adf61759a)
