### ISSUE TITLE
Support for dummy nodes count in a line

### ISSUE THREAD

**Issue by ghigi123** [erikbrinkman/d3-dag#13]
I'm having a non-fixed size graph, so I need to compute its width given the dag-layout. To do so I'd need to know how many dummy nodes there are in a given line. Could you consider adding this feature ?

**Comment by erikbrinkman** [comment]
Hey @ghigi123, I'm not sure I understand. Could you be more specific?

If just want the number of dummy nodes for a given layout, then after calling sugiyama, each node will have a `layer` attribute. `child.layer - parent.layer - 1` should be the number of dummy nodes post layout. Similarly, if you look at a `link` object (which you can get with `links()` or `childLinks()`) they each link has a `data` attribute, which may have a `points` attribute. The length of that `points` array, if it exists, is the number of dummy nodes.

If instead you want to constrain the width of every layer, then that is a little more difficult. Potentially there's a variation on Coffman Graham layering that would work for a width that includes dummy nodes, but last time I checked that wasn't super obvious.

If it's something else, please elaborate. I'm happy to help if I can.

**Comment by ghigi123** [comment]
I actually am not interested in the number of dummy nodes in a link, but on a given layer (layer is the word i meant by "line").
My computation would be :
- layer_width = sum of width of nodes + sum of width of dummy nodes
- graph_width = max of width of layers
Currently I can access dummy nodes through the separation function but it looks kind of a hacky way to access the number of dummy nodes on a given layer.

**Comment by erikbrinkman** [comment]
So, here's a quick script to calculate these from a dag.

```js
const num_layers = dag.reduce((c, n) => Math.max(c, n.layer), 0) + 1;
const layer_width = Array(layers).fill(0);
dag.each(n => { layer_width[n.layer] += 1; }); // nodes per layer
dag.links().forEach(l => l.data.points.forEach((_, i) => { layer_width[l.source.layer + i + 1] += 1; })); // dummy nodes per layer
graph_width = Math.max(...widths);
```

 It takes three iterations, but that doesn't seem that bad. I could add a function to return these / calculate them. I'm curious as to what kind of api you're looking for, because nothing seems that obvious to me. There doesn't seem to be a nice way to return these from `sugiyama`, and while this script does calculate the widths, it inherently requires that sugiyama has been run and that you're calling it from the root node, two contracts that no other api call requires.

**Comment by ghigi123** [comment]
Your snippet seems to do the job, but it does not look really straight forward to me.

I'd have imagined a "descendant" tween function, giving access to regular and dummy nodes. With a simple array of all nodes, any subsequent calculation would be made easy.

**Comment by erikbrinkman** [comment]
The problem with that API is that dummy nodes don't really exist. They're solely used for layout and then are removed, only storing their old coordinates in the edge information. I don't really like this idea of creating dummy nodes because that seems specific to sugiyama style layouts, and maybe at some point I'll add others. If I did want to add dummy nodes that were mutable, I'd have to tweak the data that's stored in points, and unless the reason is compelling I'm don't see a huge reason to.

With that in mind, can you explain why you want better access to the dummy nodes, or the width at each layer? If I knew, maybe I would understand why you want this ability and agree, or maybe I could suggest alternatives.

If you already understood the code snipped, you don't need to read this, but it's my appeal to it being straight forward. After initializing the width array to zero, it first counts how many nodes are in each layer. Then to get the dummy nodes, it iterates over all of the points (dummy nodes) in all of the edges, and computes their layer as one more than it's index in points plus the layer of its source node (`l.source.layer + i + 1`). With both, you get the full widths.

**Comment by ghigi123** [comment]
My use case is pretty simple : I want to display a graph in a svg g element, using d3-zoom. I have to choose a size for this g element so that when the graph changes, the space between nodes and links remains consistent.

Currently if I have too many dummy nodes on a line, their width is not taken into account in my computation : the real nodes on the same layer are thus getting too close to each other. (because the separation function take relative weights)

**Comment by erikbrinkman** [comment]
Sorry for the delay. So do you really just want a layout that's a fixed width including dummy nodes? There may be a way to tweak the layout algorithm to guarantee that.

**Comment by ghigi123** [comment]
Nope I want the exact opposite of a fixed width graph, I want the dummy node size to remain consistent (e.g. 20px) and thus to compute total graph width.

**Comment by erikbrinkman** [comment]
II don't understand what you mean by:

> I want the dummy node size to remain consistent 

Dummy nodes shouldn't be plotted, they only exist to render edge curvature around nodes.
I think my confusion comes from not being familiar with the way `d3-zoom` works.\
Is there a reason why something like `getBBox()` doesn't work to measure the size after rendering?
It seems like you might want something like the rendered size of the dag, which is going to change based off of the size of a node and if it exists on the edge of the dag or is internal.

If this is necessary to use `d3-zoom` on a dag, then it seems like what you're requesting should be supported in some convenient and intuitive way.

If what I'm saying still totally fails to capture what you want, I think I'm really just missing what's going on. Do you think you could post a fiddle with a minimum working example and a description of how the measurement is necessary to fix it / where it comes in?

As a side note, thanks for the patience with my understanding of the issue.

**Comment by erikbrinkman** [comment]
@ghigi123 pinging to see if I understand or not.

**Comment by erikbrinkman** [comment]
I'm still not sure I entirely understand what you want. Is the idea that you want to make sure that nodes don't overalp? For example, say you know you have at most four nodes on a line, and want to make the nodes at least 10px wide. If you set the width to 40px that should be enough, but if it ends up that there are dummy nodes on that line, then the actual nodes may be closer than 10px and therefore overlap?

If that's what the issue is, then I two different styles of solution.

1. Somewhat indirectly create a layering algorithm like Coffman Graham that also respects dummy nodes. This might be a little difficult, and isn't necessarily guaranteed to work if the minimum span with dummy nodes is larger than the number, but this could somewhat help.
2. The easier and closer solution making width optional. Currently all coordinate assignment functions take a separation function which guarantees that nodes are at least separation apart (relatively). Each function is then mandated to scale that back so that all widths are between zero and one. What we could do instead is respect the separation function fully. Have every coordinate assignment function return arbitrary x coordinates such that separation is respected. Then if width is specified it will scale them to be between zero and width, if not, just that the minimum x coordinate is zero. This will auto compute a width that allows nodes to be as wide as you want, but would also allow you to do cool things like specify a different separation based off of arbitrary sized nodes or nodes and dummy nodes. You would still need to loop over all nodes and edges to compute the width though. Although maybe there'd be some convenient way to return it.

If I'm still way off, a fiddle might help, although I think I'm still struggling with what you ultimately want to achieve.

**Comment by ghigi123** [comment]
Hey, sorry for the delay, I have been working on something else for the past few months.
I think you got the issue, the first sentence is ultimately what i want to do.
Given a number of nodes and their width on a line, I just need them to respect this defined width, without overlapping, even if many dummy nodes add some width to the total layer width

**Comment by erikbrinkman** [comment]
I guess to me overlapping is hard, as nodes don't inherently have a size in the layout. I think I see what you mean, you want the maximum width of the layout including dummy nodes so that you can set `radius = width / (maximumNodeWidth * 2)`. Potentially something that makes more sense would be a minSeparation function that return the minimum separation between all adjacent nodes after layout? Both should be possible, the latter seems more relevant to what you actually care about, and scales to work even if alternate separation oracles are used.

**Comment by ghigi123** [comment]
Instead of defining the node radius afterwards (radius = ...), as my nodes have fixed content, and thus computable content width, i want to define the graph size afterwards (width = sum of custom node widths + separation * (number of nodes + number of dummy nodes) + dummy node width * dummy node count)

**Comment by ghigi123** [comment]
In d3-hierarchy, you can set size to null so that the nodeSize is used to compute the layout total size
https://github.com/d3/d3-hierarchy#cluster_size

**Comment by erikbrinkman** [comment]
Yeah, that seems like the correct way to go. Both to mimic hierarchy, and scale output based off of node size. I'm not really sure when I'll get around to this, but I do ultimately want to have some api like you're describing, probably as the default, since it seems like that's what most people want.
