### ISSUE TITLE
Preventing node overlap on complex graphs

### ISSUE THREAD

**Issue by strass** [erikbrinkman/d3-dag#18]
I'm having trouble preventing node overlap on complex graphs and I'm not sure what the best avenue to correct it is.

I am generating DAGs and using the layout's layers + nodes per layer to dynamically compute width and height based on node size and a separation value. This works well with smaller graphs but as complexity increases my nodes don't seem to be utilizing space well:

![2019-04-10-125051_192x305_scrot](https://user-images.githubusercontent.com/134242/55897909-7e5d3780-5b8f-11e9-9fcc-76bd1d8ddb3c.png)
![2019-04-10-125105_644x309_scrot](https://user-images.githubusercontent.com/134242/55897910-7e5d3780-5b8f-11e9-8772-ddba6c772c57.png)

There's more than enough space to separate those tightly packed clusters of nodes but I'm not having much luck figuring out how to do it well over a variety of graph complexities.

Should I explore the coord accessors or is this something that the separation function takes care of? How do I specify that the separation between nodes should be at least the node width + a separation value that I specify?

These layouts are being generated by the react hook below:
```
import { useMemo, useEffect, useState } from 'react';
import * as d3dag from 'd3-dag';
import { groupBy, map } from 'lodash';

const dagStratify = d3dag.dagStratify();

export default function useSugiyamaDag<DT>(
  data: NodeDef<DT>[],
  {
    nodeWidth,
    nodeHeight,
    nodeSeparationX,
    nodeSeparationY,
  }: {
    nodeWidth: number;
    nodeHeight: number;
    nodeSeparationX: number;
    nodeSeparationY: number;
  }
): UseSugiyamaDagOut<DT> {
  // Start with width and height of 0. This gets overwritten below
  const [width, setWidth] = useState(0);
  const [height, setHeight] = useState(0);

  // Re-stratify data + remake layout fn whenever changes are detected
  const dag = useMemo(() => dagStratify(data), [data]);
  const layout = useMemo(() => {
    console.warn('(Re)creating DAG layout function');
    return (
      d3dag
        .sugiyama()
        // .debug(true)
        .size([width, height])
        // .layering(d3dag.layeringLongestPath())
        // .coord(d3dag.coordCenter())
        // not sure if this is working
        .separation((_a: {}, _b: {}) => nodeWidth + nodeSeparationX)
    );
  }, [width, height, nodeWidth, nodeSeparationX]);

  // Layout the tree
  const { tree, descendants, descendantsByLayer } = useMemo<{
    tree: UseSugiyamaDagOut<DT>['tree'];
    descendants: {}[];
    descendantsByLayer: Record<number, {}[]>;
  }>(() => {
    console.warn('Laying out DAG');
    const t = layout(dag);
    const d = t.descendants();
    const dBL = groupBy(d, n => n.layer);
    return { tree: t, descendants: d, descendantsByLayer: dBL };
  }, [layout, dag]);

  // Calculate and set height and width of the graph dynamically
  useEffect(() => {
    // Start with width and height of 0. This gets overwritten below once layout has been computed
    const newHeight =
      Object.keys(descendantsByLayer).length * (nodeHeight + nodeSeparationY);
    // Find each layers width (number of nodes per layer * width of each node) and
    // set the overall width to the max computed layer width
    const newWidth = Math.max(
      ...map(
        descendantsByLayer,
        layer => layer.length * (nodeWidth + nodeSeparationX)
      )
    );

    // Set height/width if values don't match
    if (height !== newHeight || width !== newWidth) {
      setHeight(newHeight);
      setWidth(newWidth);
    }
  }, [
    descendants,
    descendantsByLayer,
    height,
    nodeHeight,
    nodeSeparationY,
    nodeWidth,
    width,
    nodeSeparationX,
  ]);

  return { height, width, tree, descendants };
}

export interface NodeDef<Data extends {}> {
  id: string;
  parentIds?: string[];
  data: Data;
}

export interface LayoutNodeDef<DT> {
  id: string;
  layer: number;
  x: number;
  y: number;
  children: LayoutNodeDef<DT>[];
  data: NodeDef<DT>;
}

interface UseSugiyamaDagOut<DT> {
  height: number;
  width: number;
  tree: {
    links: () => {
      source: LayoutNodeDef<DT>;
      target: LayoutNodeDef<DT>;
    }[];
    descendants: () => LayoutNodeDef<DT>[];
  };
  descendants: {}[];
}
```

**Comment by erikbrinkman** [comment]
Unfortunately, the separation accessor only does relative separation, so if you set it to a constant, nothing will happen. One thing that will help a layout with this many edges is to set the separation so that dummy nodes (e.g. nodes used to wrap edges around nodes) either have 0 separation or zero separation around each other. See the updated documentation for the separation accessor for more info.

Since you're not currently rendering the edges according to their curvature, the easiest thing to do to produce a nice layout would be to ignore edges by setting separation to
```
function separation(a, b) {
  return +(a.data !== undefined and b.data !== undefined);
}
```

The other thing you can do is set a better coordinate accessor, which defaults to center because it's fast.
I usually find that setting it to `d3.coordVert()` produces the best results, but may be a bit expensive. If you find it's taking too long, try `coordGreedy()` instead.

I imagine both of those changes should solve your immediate problems. However, you're not the first person who has wanted to set a concrete separation between nodes, and adjust the width / height of the graph to match that separation. I don't think I'll have time to set that soon, but you can always scale the x or y coordinate after rending, relatively easily. That's basically how width and height are handled internally anyway.

If you think the documentation was unclear, or there are ways the readme could be better, please submit a pr to clear things up. Also, let me know if this didn't solve the problem.

**Comment by strass** [comment]
I see, thank you for expanding on the separation function.

When I try your suggestion above `return +(a.data !== undefined and b.data !== undefined);` (swapping `and` for `&&`?) my overlapping problem gets worse (see layer 3 column 2):
![2019-04-11-100731_644x313_scrot](https://user-images.githubusercontent.com/134242/55963978-cdfc3b80-5c41-11e9-81ff-689976f769b5.png)


The other separation function `return (a.data !== undefined) + (b.data !== undefined);` looks much better:
![2019-04-11-100243_557x260_scrot](https://user-images.githubusercontent.com/134242/55963920-a9a05f00-5c41-11e9-833d-258bbc2af855.png)

I added an extra feature where clicking on a node highlights connected edges. This may have been a problem before but as you can see in the image above, `c` (layer 1 column 5)'s connection to `e` (layer 4 column 1) passes through 2 nodes and if I didn't have a highlight feature, it would be very difficult to tell that it's not connected to `v` and `m` along the way. Any suggestions?

Thank you very much for your thoughts :)

**Comment by erikbrinkman** [comment]
After looking at it again, I realized the second suggestion is just wrong, but clearly the first works well. Also yes `&&`, I've been writing too much python...

When it comes to the edges, part of the layout algorithm is computing a path for edges to wrap around nodes. If you look into the documentation (because I forget the actual api) there are methods get `link` objects, which contain the `source` and `target` nodes as well as `data`. After running the layout, the link data will contain a series of points that can be used to render a path that weaves around nodes instead of intersecting. Using the `vert` layout tries to minimise the curvature of those links, but ymmv, and it may produce a more jumbled layout if you want to pad the edges with a different separation function.

Also, let me know if everything is addressed so I can close this issue. Thanks!

**Comment by strass** [comment]
Yup this has been great. Thanks for the explanations.
