### ISSUE TITLE
Collapse/minimize subgraphs?

### ISSUE THREAD

**Issue by greencat3** [erikbrinkman/d3-dag#23]
Does d3-dag have any in-built functionality to be able to minimize/collapse subgraphs?

I saw this demo of collapsible trees on d3: https://observablehq.com/@d3/collapsible-tree

Is it possible to do something like this with d3-dag?

Also, can you use a dom node as a graph node? Say I build an elaborate HTML node with input elements and few images, can I use this dom node as my graph node?

**Comment by erikbrinkman** [comment]
1. The observable ones are the best, in that they're up to date. Here is an old [example](https://jsfiddle.net/ye2xanf9/77/), but I don't know how to get jsfiddle to load the old version of the repo, so it doesn't work as is. Maybe that will help? Alternatively, for observable you should be able to just edit each individual cell. For your purposes, only the top one should be the only one that matters, as everything else is just set up. This is only designed for a static representation, so the edits to make it dynamic will probably be significant.

2. Yes, exactly. Especially if you want a smooth transition as a node grows larger, rerunning the layout several times would be prohibitive. You could probably just compute a beginning and end state, and transition though.

3. I vaguely understand what you're going for, but not enough to really advise what's appropriate. The two layout algorithms that I contributed don't allow for nodes that span several layers. Arquint recently contributed something like this, but I don't know much about it, other than it works. The reason why I say this now is that before you start tweaking, you should understand the design and limitations of the current algorithms. Put another way, these are designed for static layouts, so instead of trying to hack them into a dynamic layout, it may be better to envision the type of layout you want, and then start adding pieces from the library to get there.

**Comment by BenPortner** [comment]
@greencat3 
Just found your issue. I built a collapsible family tree using of d3-dag. Maybe this helps you?

https://github.com/BenPortner/js_family_tree

It is collapsible in all directions (clicking on a node will collapse parents, children and partners). You said you want to collapse only subgraphs. I think it should be fairly easy to adapt my code that way. Let me know if you have any questions!

Cheers.
Ben

**Comment by erikbrinkman** [comment]
I'm closing this as I think collapsibility is not in scope for what this project should do. Some that's in scope and relateates to this would be some form of stable layout. I don't have a good definition of what that would actually entail, and so I'm not going to open up an issue, but if that was of interest, and you could describe something implementable that would accomplish some notion of stability, I'd be interested.
