### ISSUE TITLE
Support for clustering 

### ISSUE THREAD

**Issue by zmitry** [erikbrinkman/d3-dag#7]
Do you plan to add support for nodes clustering ?

**Comment by zhDmitry** [comment]
Ok, fair enough. It not so easy to add clustering support. Maybe you have some ideas how can we get layout with clusters maybe with some kind of hack ?

**Comment by erikbrinkman** [comment]
It depends on what you need to do. In principle, clusters are just laid out first, so if you want to create a clustered layout, you could just do the layout hierarchically. First layout each cluster. Then replace them with single nodes and lay those out. You'll need to do some adjustment so everything fits, but that's how I would approach this from a hacking perspective.

**Comment by ghigi123** [comment]
Here is a nice approach about how to render compound directed graphs, which is I think a bit different from first layouting clusters.

https://publikationen.sulb.uni-saarland.de/bitstream/20.500.11880/25862/1/tr-A03-96.pdf

**Comment by erikbrinkman** [comment]
@ghigi123 Thanks for the link. I think support for this is definitely worth it, although I wonder how much it's worth reimplementing all of this, or if it makes more sense to find a way to use something like graphviz on the backend.

Also, I'm not sure when / if I will have time to work on support for something like clustering.

**Comment by GordonSmith** [comment]
I would second support for this - sample use case:  https://play.hpccsystems.com:18010/?Wuid=W20190503-171109&GraphName=graph2&SafeMode=false&Widget=GraphTree7Widget

**Comment by gareth-lloyd** [comment]
I did some more experimentation. I can define union nodes that express the relationship between two individuals, and then express the relationship to their children as a parent-child relationship from the union to each child.

```
    parent A -- Union -- parent B
                |
        --------------
        |            |
        Child C     Child D
```

The trouble then is that A and B's relationship to Union is parent-child, not sibling, so union is drawn at the next level of the graph. The arrangement is more like this:

```
    parent A           parent B
       |                 |
        ---- Union ------
                |
            -----------
            |          |
        Child C     Child D
```

**Comment by erikbrinkman** [comment]
@gareth-lloyd it's reasonable to not know about this, as it's kind of hidden in the library, but the simplex layering operator has a [rank option](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering_simplex.simplexoperator.html#rank). I don't think it's super tested (and doesn't appear to be well documented either), but essentially you can define a rank for each node, nodes with the same rank will get the same layer, otherwise, nodes with higher ranks will be further down. If that is too strict for you, you then I would recommend copying the source code and tweaking it to just enforce equality on the nodes you want to be equal. Note, this only works for simplex layering, as the other operators don't really have a way to enforce this constraint.

Also, if you have further questions about this, it's not really related to this type of clustering, so I would open up a new issue to keep things separate.

**Comment by erikbrinkman** [comment]
This has been open for five years, and supporting it would still be very difficult and I have no direct plans to. If you're still looking for clustering support you've hopefully moved on long ago 😢

**Comment by adminy** [comment]
There is https://dagrejs.github.io/project/dagre-d3/latest/demo/clusters.html

Although it is got some bugs.
