### ISSUE TITLE
Cleanly handling cycles in input graphs

### ISSUE THREAD

**Issue by curiouserrandy** [erikbrinkman/d3-dag#80]
DAGs by definition have no cycles.  But many real world entity relationship diagrams do have cycles, even if there is an underlying hierarchy that tends to reduce the number of such cycles (e.g. call graphs or type reference diagrams in program static analysis).  It would be useful if d3-dag had the ability to handle cycles in some fashion.

My understanding of how Graphviz handles cycles is that it does a pre-pass over the input data figuring out the minimum number of edges whose directions have to be reversed in order to turn an input cyclic graph into a DAG.  That DAG is then layed out, then the edges that were reversed before are re-reversed so the output looks as expected by the user.  Any chance d3-dag could do something similar?

**Comment by erikbrinkman** [comment]
I've thought about this, and it's mentioned anywhere dag layouts are. My first thinking was that d3 already had general graph libraries, and if you wanted to render a general graph you would use those. As far as near dags, that's a good point, and it shouldn't be too hard to do exactly that, find a small or smallest number of inversions to make a dag directed, e.g. flip one edge in each cycle.

I had stalled because I wasn't sure how to render it, but links already have a bunch of ancillary data, e.g. next, data, points. It would be non-breaking to also add "flipped" or "reversed" to indicate that that edge actually goes the opposite direction.

Which means I think implementation I'm thinking of would add a cycle resolution policy to all dag creation methods. This could be error (don't allow cycles), opt (minimize the number of flips), fast (work, but don't take forever). I'm not sure I'll need fast, but sometimes tells me worst case the minimum number of inversions is np-complete. And the inverted edges would get a property saying they were inverted. Does this sound reasonable?

**Comment by curiouserrandy** [comment]
That all makes sense to me.  I've spent some time musing on what the "find the edges to flip" algorithm would look like, but haven't made any progress, and eventually decided that if I wanted to actually solve the problem I should look up the previous work in the space :-}.  But I wouldn't be at all surprised if you needed "fast", and if it ended up being the commonly used option for graphs that may have cycles.

I'm intrigued by your statement that d3 already has general graph libraries, since I spent some time searching through those for something I could use before looking outside of the base library.  Do you mean something other than a force directed layout?  I found the d3 library support sadly lacking for directed graphs with potentially lots of crossings (really, for any graph that wasn't close to planar).

(This discussion does make me want to better characterize the graphs I'm usually wanting to display.  I've thought of myself as exploring general entity relationship visualization, but I've also generally been dissatisfied with non-hierarchical displays.  Maybe the issue is that the data I'm working with is more specialized than I think.  Certainly programmatic call graphs are usually near-dag, and type system relationships may be as well.  Something for me to think about.)

**Comment by curiouserrandy** [comment]
One other comment: I had the thought after I filed this issue that this feature could be easily implemented outside of the library by the consumer doing a pre-layout step and tracking which links they flipped.  I think it still makes sense to implement it in the library (both because it's "layout expertise" that's required to implement it, which it makes sense to provide in the library, and because I think there are many more near-dag applications than pure dag applications for visualization).  But if you wanted to keep it outside the library, I think that's a reasonable position.

**Comment by erikbrinkman** [comment]
I totally agree with the later comment, I think that's why I wasn't an immediate rush. Fortunately d3-dag allows you to attach arbitrary data to things (like d3-hierarchy) so you can flip edges and then make sure that the edge data includes reversal for layout, but I was ultimately swayed by your point that there are things that are "near" dag, and it doesn't really make sense for everyone to rewrite edge swapping, especially since there don't seem to be many javascript dag libraries in general.

As for other graph libraries, I found at least one other general graph layout algorithm buidl around d3. I think the real difference is libraries meant around large scale graph exploration, and the problem there is that this is still an open problem...

**Comment by alanricheh333** [comment]
Hello, I am very interested in having cycle support. How difficult would this be to implement? Do you @erikbrinkman  have the time to implement it yourself? If not could you give pointers on how to do it?
It would be much appreciated.

**Comment by curiouserrandy** [comment]
For what it's worth, I believe I've found where Graphviz implements this (https://gitlab.com/graphviz/graphviz/-/blob/main/lib/dotgen/acyclic.c).  I haven't had a chance to dig in and understand the algorithm yet though.

**Comment by erikbrinkman** [comment]
@curiouserrandy thanks for the pointer! That looks relatively simple, I guess because they're not looking to do something optimally. This becomes hard to do optimally because inverting one edge can affect multiple cycles, and you in principle need to see if reversing an edge will cause you to create another cycle.

@alanricheh333 I do plan on implementing this. @curiouserrandy has been great at pointing out a lot of ways to improve the library, but I still have limited time. This is probably more straightforward, so will probably be done first, but I don't have a strict time frame.

Beyond the source example, I'm sure there are other descriptions of graphviz's algorithms that I would look to. After looking into a bit, the problem is called the "feedback arc set problem", and you can find papers like [this](https://researchrepository.murdoch.edu.au/id/eprint/27510/) talking about one approximate solution (which looks potentially like the version implemented by graphviz).

**Comment by curiouserrandy** [comment]
Duplicating relationship between issue #85 and this one here: A simple cycle (A -> B -> A) could turn into multiple paths from a parent to child (A -> B, A -> B), so we might want to consider handling the latter case as part of handling the cycle issue.

**Comment by MShekow** [comment]
Support for cycles would indeed be very useful. Looking forward to it! Thanks Erik for looking into it.

**Comment by erikbrinkman** [comment]
Sorry for the delay on this, I've been busy with other things. Support for cycles should no be in master. Each dag creation method has a `.decycle(true)` option that will remove cycles and add a `reversed: True` property to any links it had to reverse. It's up you in the layout to render it differently (e.g. with a reversed arrow).

There are a few breaking changes that can be seen in the new changelog. Most usages should be unaffected, but if I do a cut I want to bump the version, and since I'm still working on some things around dynamic updates I might introduce more changes before doing a full cut, since I've played so fast and loose with breaking changes.

You should be able to test it by building locally, but if anyone is having issues feel free to comment here.

**Comment by curiouserrandy** [comment]
Thanks very much for this change; I'm excited to try it out!  And I don't think it's going to be hard to try out, since my test data has cycles and the only reason I haven't run into problems so far is that I'm interactively specifying which sections of the graph to actually layout :-}.

My apologies for the naive question, but do you have any pointers for building and running locally?  I'm not very familiar with JS build conventions (and not at all with TS build conventions) and glancing at the d3-dag checkout I don't see a Makefile or anything like that *and* I'm not sure of the best syntax to load from a local web server--the example I'm copying from uses require, which doesn't appear to take a URL.  Can you easily point me to an example or breadcrumbes for building and loading locally?

**Comment by erikbrinkman** [comment]
It's built using `esbuild`, and triggered through yarn. If it's checked out you should just need to run `yarn install && yarn build && yarn bundle` to create the bundled outputs in `bundle/`.

If you're just testing with observable, I can attach a built version. Github won't let me upload js, but here's the built esm version that's also zipped. To use in observable simply replace the part where d3Dag is imported with 

`d3Dag = await import(await FileAttachment("d3-dag.esm.min.js").url());`

[d3-dag.esm.min.zip](https://github.com/erikbrinkman/d3-dag/files/8144910/d3-dag.esm.min.zip)

and you should now have access to decycle and multifags, among other improvements. If you want documentation, simply check this out and run `yarn install && yarn doc` then start a file server from the `docs` directory.

**Comment by curiouserrandy** [comment]
Thanks very much for the help!  My apologies in advance, since I think "pilot error" is the most likely explanation for this, but I'm getting a "TypeError: d3.dagStratify(...).decycle is not a function" error when I try this.  Am I holding it wrong?  https://observablehq.com/@curiouserrandy/initial-interactive-graph-explorer.  I just republished, so you can probably see the error; the relevant cells are "create_op_stratify" and "d3".   I skimmed the source, and it looks like d3.dagStratify() should be returning an object with the decycle method on it.  But I believe my attachment is what I get when I unzip what you provided above. 

(I do want to eventually be able to run based on a local build, but I don't have nodeJs/yarn installed, so going with your uploaded .zip seemed the quickest way to try things out.)

**Comment by erikbrinkman** [comment]
Sorry, I should have been more clear. `import` works fine with esm, so you don't need the iife trick. Instead of
```
  // observable doesn't like iife, so we have to ignore the "real" importing and grab the object from window
  const d3Dag = await import(
    await FileAttachment("d3-dag.esm.min.js").url()
  ).then(() => window["d3"]);
```
you should just have
```
  const d3Dag = await import(
    await FileAttachment("d3-dag.esm.min.js").url()
  );
```

**Comment by curiouserrandy** [comment]
Thanks, all set now, and it appears to work fine!
