### ISSUE TITLE
Individual edge verticality

### ISSUE THREAD

**Issue by shatgupt** [erikbrinkman/d3-dag#81]
I see that we already have a way to define weights for verticality in QuadOperator but that is applied to all the edges in the DAG. Is there a way to do it individually such that I can define which edges should be vertical and which ones may not? I am looking for a layout similar to following. The blue edges connecting A_*, B_*, C_* nodes must be vertical and other edges can be non-vertical. This was [generated using Graphviz's dot engine](https://edotor.net/?engine=dot?engine=dot?engine=dot#digraph%20%7B%0A%20%20A_1%20-%3E%20A_2%20%5Bcolor%3D%22blue%22%20weight%3D20%5D%0A%20%20A_2%20-%3E%20A_3%20%5Bcolor%3D%22blue%22%20weight%3D20%5D%0A%20%20A_1%20-%3E%20B_2%20%5Bcolor%3D%22red%22%5D%0A%20%20B_1%20-%3E%20B_2%20%5Bcolor%3D%22blue%22%20weight%3D20%5D%0A%20%20B_2%20-%3E%20B_3%20%5Bcolor%3D%22blue%22%20weight%3D20%5D%0A%20%20B_2%20-%3E%20C_1%20%5Bcolor%3D%22red%22%5D%0A%20%20B_2%20-%3E%20A_3%20%5Bcolor%3D%22red%22%5D%0A%7D%0A) by specifying higher weights for the blue edges.

![Screen Shot 2022-01-25 at 6 59 25 PM](https://user-images.githubusercontent.com/2388644/151096778-b6f6b7bc-3d25-49a4-a89c-e20b6b635e8f.png)

**Comment by erikbrinkman** [comment]
Unfortunately, that's not possible right now, but it shouldn't be too difficult to add.

Here is where the objective is defined:
https://github.com/erikbrinkman/d3-dag/blob/096b0c55442e83a97dc7700b78ccc4bed36344f5/src/sugiyama/coord/quad.ts#L164-L169
all you'd need to do is instead of adding the weight of both nodes, as defined, would be to call some function of the link instead.

I'm both swamped right now, and need to think a little about what the appropriate api would be, although I'm open to suggestions.

If you want to do something quickly, you should be able to basically copy the quad source code, and import the necessary utilities from the `dist/sugiyama/coord/...` directory, allowing you to specify the weights for edges arbitrarily.

If you want to throw together PR, that's welcome too, but I will get around to this as soon as I have time.

**Comment by erikbrinkman** [comment]
@shatgupt as of version `0.10.0` quad now has support for increasing the verticality of certain lines, and I added a new coordinate assignment algorithm that's based on the way dot does it, that also has support for link level adjustments to verticality.
