### ISSUE TITLE
Connect data format has no way for specifying node data in resulting dag

### ISSUE THREAD

**Issue by curiouserrandy** [erikbrinkman/d3-dag#83]
As best I could tell, there's no way to bind data (for use by .data() when doing graph drawing based on the layout) to the resulting dag using Connect data input format (https://erikbrinkman.github.io/d3-dag/interfaces/dag_create.ConnectOperator.html).  I'm not sure from the documentation if there's a way to bind data to the edges either.  

It's not particularly hard to switch the data input format over to stratify, which does allow for such specification, but it seems an odd lack.  

(This isn't high priority for me--I've done the input data format switch--but I figured if I ran into a hole in the API it's worth calling out.)

**Comment by erikbrinkman** [comment]
`connect` does add edge data, which is whatever you pass in. IF you call connect on the default input, something like: `["1", "2"]` each edge will have that as data. I guess this does seem like hole in the api, but I didn't include it since in the standard data format, each node is included several times, and it seemed weird to have a separate data structure that just has the node data.

are you imagining something like `connect()([["1", "2"]], {"1": { ... my data }})`?

currently since each node must have an id, that's what's put in the data, e.g. `{ id: ... }` How should this be treated with any new data someone supplies? Should you be allowed to overwrite the id? Should id be ignored? Should an error be thrown? These are all questions I thought didn't have good enough answers to bother complicating the api, but I'm always welcome to suggestions. The implementation itself isn't that hard.

But yes, what I had in mind was that if you needed node data, you could just switch to a different creation method.

**Comment by curiouserrandy** [comment]
I think making people use another input format if they want node data is a reasonable option.  I slightly dislike it because of API parallelism, but it doesn't affect the usability of the library really any at all.  If you want to do that, I'd just call out that you can't associate node data in the documentation for the Connect data operator and call it a day.

If you do want to implement this, in term of how to associate the data, you could have an (optional) array of objects with a (mandatory) id: member.  This brings up the question as to what you do if the user doesn't supply data for all the ids (which I think is an issue for your other option above), but I think either not assigning data in that case or throwing an error would be equally valid options.  I lean towards not assigning data; the only reason I raise throwing an error is that the expected usage in d3 would probably be a parallel operation that expects to find data on all nodes, and it's better to find out about errors earlier in the process rather than later.  But now I'm overthinking it :-}.

**Comment by erikbrinkman** [comment]
I now added support for this in the way that seemed most stylistically appropriate. you can add a callback that generates data conditioned on the id, which you could tie back to your own map or use some other method.

Like the other aspects, this is only on master.

**Comment by curiouserrandy** [comment]
Thanks!  But yeah, it's not particularly harder for me to generate stratify data format, so I'll probably just stick there (though if there's value for you in my testing out the new input format let me know and I'll switch back).
