### ISSUE TITLE
TS, export SugiNode<NodeDatum = unknown, LinkDatum = unknown> ?

### ISSUE THREAD

**Issue by chtimi59** [erikbrinkman/d3-dag#88]
unfortunatly, this doesn't works:
```
import { SugiNode } from 'd3-dag';
```
This Type would be needed to add my own `decross()` method

**Comment by erikbrinkman** [comment]
It's not exported directly, but assuming you're building with node you should be able to do

```
import { SugiNode } from 'd3-dag/dist/sugiyama/utils';
```

using the "experimental" es6 declarations. Note that the internal filepaths are generally subject to change, so if you do use it, you'll want a hard pin.

Alternatively, the definition is not complex, so you could just copy it. Typescripts structural typing should handle that fine:

https://github.com/erikbrinkman/d3-dag/blob/9cbb20c965baeadb71412d647170bf8bd5020c54/src/sugiyama/utils.ts#L23-L34

I think I avoided exporting it because of polluting the namespace, but that's actually less of an issue for types, so I'll add it in a patch release.

**Comment by chtimi59** [comment]
Yes, in the meanwhile that's what I have made (the copy/past) solution

**Comment by erikbrinkman** [comment]
I have also released a patch version that has it. Anything after 0.11.2
