### ISSUE TITLE
TS Sugestion(?)

### ISSUE THREAD

**Issue by chtimi59** [erikbrinkman/d3-dag#89]
Since DAG is a kind of mix definition of layouted DAG and pure DAG définition.
I suggest to export the following type gard:

```ts
type DagLayoutedNode<NodeDatum, EdgeDatum> = DagNode<NodeDatum, EdgeDatum> & {
    value: number,
    x: number,
    y: number
}

function isLayoutedNode<NodeDatum, EdgeDatum>(node: DagNode<NodeDatum, EdgeDatum>): 
   node is DagLayoutedNode<NodeDatum, EdgeDatum>
{
    return node.value !== undefined && node.x !== undefined && node.y !== undefined
}
```

Hence, for example iterators may becomes 
```ts
 const list : number[] = this.dag.descendants().map(node => {
    assert(isLayoutedNode(node));
    return node.x; // node has DagLayoutedNode type
});
```

**Comment by chtimi59** [comment]
> Thoughts?

Not really, in my mind, you ask yourself the right questions ! :)
But that say I would be quite happy with option 2

**Comment by erikbrinkman** [comment]
I know it's been a long time since I last responded to this, I've been working on some massive rewrites to allow things to be more dynamic.

For many of the reasons outlined above, I don't think it really makes sense to add a new type definition. Originally I did work on a version that returned a new graph via unsugify. This would be fine the way the library currently works, but with the dynamic use case it makes things much more complex to still maintain d3 data binding, so I ultimately scrapped it. What I've chosen to go with is two separated properties:

1. a raw property that can be undefined called `ux` and `uy`
2. a corresponding getter and setter that only accepts numbers, and raises an exception if the properties are `undefined`

This isn't ideal in that is still requires runtime knowledge that the dag has been laid out, but you now no longer need non-null asserts, and it gives freedom in interface, e.g. you can still use ux and uy if you want to be safe.

Does this address your use case, or do you think there is still a better solution out there?

**Comment by erikbrinkman** [comment]
This standard is now implemented in the prerelease. x and y are always numbers, but will throw if the underlying ux or uy is undefined.
