### ISSUE TITLE
Possible linking bug in docs

### ISSUE THREAD

**Issue by coconutlad** [erikbrinkman/d3-dag#91]
Hi,
I think there may be a bug in linking within the docs for Sugiyama layering operators.

[The page for `LayeringOperator`](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering.LayeringOperator.html) has possible inconsistencies with its links.

The hierarchy section looks like this:
> LayeringOperator
        [CoffmanGrahamOperator](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering_coffman_graham.CoffmanGrahamOperator.html)
        [LongestPathOperator](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering_longest_path.LongestPathOperator.html)
        [SimplexOperator](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering_simplex.SimplexOperator.html)

where simplex operator links to the sugiyama layering simplex operator.

On the other hand, the section under "Callable" has slightly different links:
> [LongestPathOperator](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering_longest_path.LongestPathOperator.html) - minimum height layout
    [CoffmanGrahamOperator](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_layering_coffman_graham.CoffmanGrahamOperator.html) - fixed node with layout
    [SimplexOperator](https://erikbrinkman.github.io/d3-dag/interfaces/sugiyama_coord_simplex.SimplexOperator.html) - minimize the length of edges
    [TopologicalOperator](https://erikbrinkman.github.io/d3-dag/modules/sugiyama_coord_topological.html#TopologicalOperator) - topological layering (one node per layer)

Here the `LongestPathOperator` and `CoffmanGrahamOperator` link to their respective sections under **sugiyama layering** but the `SimplexOperator` and `TopologicalOperator` link to the **sugiyama coord** section. 

In case this is a bug, maybe it's because the "link id" for both of the simplex operators have the same name?  
[coord](https://github.com/erikbrinkman/d3-dag/blob/1f705a3ec0d89a218046010cb5d745bfa9b1fc54/src/sugiyama/coord/simplex.ts#L2) and [layering](https://github.com/erikbrinkman/d3-dag/blob/1f705a3ec0d89a218046010cb5d745bfa9b1fc54/src/sugiyama/layering/simplex.ts#L2)
Sorry I couldn't figure out much else, I'm not familiar with this docs generation tool.

**Comment by erikbrinkman** [comment]
Unfortunately, I think this is probably under the category of known issue. `typedoc` only supports [limited link resolution](https://typedoc.org/guides/link-resolution/), despite the tsdoc spec generally supporting [qualified links](https://tsdoc.org/pages/tags/link/). This is also partially a problem with the way d3-dag is structured. It's both a modular library that anyone can use as a typescript project, hence the goal to document and export internal things, but it's also a front end library with only one entry point `index.ts`. This structure isn't good for typedoc.

As I see it, there are three solutions:
1. wait until typedoc fixes this - it's been years so maybe not the best option
2. rename the internal types to be unambiguous - I dislike this because it's technically breaking, although only to people using the ES6 syntax, it's also more verbose, but maybe that's not a bad thing. I'm leaning towards this as the best option, that way I don't have to rename them at export and it solves this problem.
3. link to the unambiguous export names - this will also fix it, but creates a two link problem where you have to click once to get to the exported name, and then again to the internal definition, which isn't great...

I have a few other projects I'm working on that are a little higher priority for me, but I'm planning to put some more cycles here soon, particularly if you end up having comments on interactive dags, because it would be nice to shore up that in terms of the api. If I do that, it probably makes sense to break this internal api as well.

**Comment by erikbrinkman** [comment]
In the lastest version, I changed to a flat documentation structure that typedoc prefers, and changed the names of things to be more verbose, but legible in a flat module structure. This also fixed the aliasing issue.
