### ISSUE TITLE
Layout direction

### ISSUE THREAD

**Issue by antoine-duc** [erikbrinkman/d3-dag#99]
Hello,

I have to implement a DAG vizualisation from left to right instead from top to bottom.
Is there an option for this?

Regards

**Comment by erikbrinkman** [comment]
Yes! It's not super well documented, but I hope to make it a little more straightforward soon. Essentially x and y are just labels on each piece of information. If you want it rendered left-to-right simply replace x with y, width with height, and vice versa.

You can see an example [here](https://observablehq.com/@erikbrinkman/d3-dag-topological) if you click "horizontal" down at the bottom.

Note however that currently variable height (width if rendered rtl) are not well support currently (each layer will just have the maximum height over that layer). I say this because if you're adjusting node sizes based off of text, it probably won't render very compactly. A solution is in the works though...

**Comment by antoine-duc** [comment]
Thanks for your quick answer and for your job with this library.
That's what I was planning to do but I wanted to be sure.
